# Generated by Django 4.2 on 2023-04-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=8)),
                ('telefono', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_nacimiento', models.DateTimeField(verbose_name='fecha de nacimiento')),
                ('fech_public', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
